services:
  db:
    image: postgres:16.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0' -p 3001
    volumes:
      - .:/abboo
    ports:
      - '3001:3001'
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  postgres_data:
